# Generated by Django 4.1.7 on 2023-02-24 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import showcase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_ru', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_en', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('in_stock', models.BooleanField()),
                ('quantity', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Toy slug')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=showcase.models.path_and_rename)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.categories')),
                ('category_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.categories')),
                ('category_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.categories')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.materials')),
                ('material_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.materials')),
                ('material_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.materials')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.sizes')),
                ('size_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.sizes')),
                ('size_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.sizes')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('preferable_messenger', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('Email', 'e-mail')], default='em', max_length=10)),
                ('order_type', models.CharField(choices=[('New toy order', 'New'), ('Toy from shop', 'Exist')], max_length=30, null=True)),
                ('comment', models.TextField(max_length=500, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('purchase_exist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='showcase.toy')),
            ],
        ),
    ]
