# Generated by Django 4.1.7 on 2023-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Toy slug'),
        ),
    ]
