# Generated by Django 4.1.7 on 2023-03-05 21:16

from django.db import migrations, models
import showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=showcase.models.path_and_rename),
        ),
    ]
