# Generated by Django 4.1.7 on 2023-02-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='material_en',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='material_ru',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='price_ru',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='material_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='material_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
