# Generated by Django 4.1.7 on 2023-02-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_remove_toy_category_en_remove_toy_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='material_en',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='material_ru',
        ),
        migrations.AddField(
            model_name='toy',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.categories'),
        ),
        migrations.AddField(
            model_name='toy',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.categories'),
        ),
        migrations.AddField(
            model_name='toy',
            name='material_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.materials'),
        ),
        migrations.AddField(
            model_name='toy',
            name='material_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.materials'),
        ),
        migrations.AddField(
            model_name='toy',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
