# Generated by Django 4.1.7 on 2023-02-15 23:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_toy_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('preferable_messenger', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10)),
                ('order_new', models.TextField(max_length=500, null=True)),
                ('comment', models.TextField(max_length=500, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('purchase_exist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='showcase.toy')),
            ],
        ),
    ]
