# Generated by Django 4.1.7 on 2023-02-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_feedback'),
        ('showcase', '0004_remove_order_order_new_order_order_type_and_more'),
    ]

    operations = [
    ]
