# Generated by Django 4.1.7 on 2023-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_remove_toy_category_en_remove_toy_category_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
